### ISSUE TITLE
Not working with Grafana v7.0.6

### ISSUE THREAD

**Issue by MaxFloatiliy** [flespi-software/flespi-devices-grafana-datasource#3]
Hello, 

i really like flespi and Grafana, but since Version 7. This data source plugin is not working any more. You cant select parameters, looks like the new grafana version needs some changes to the plugin. See Screenshot:
![grafana-flespi](https://user-images.githubusercontent.com/59435011/90982568-28ace380-e568-11ea-81f4-f2d3220b18f2.png)

**Comment by dexif** [comment]
I'm sorry. At the moment we do not have resources to adapt the plugin to new versions of Grafana.
You can fix plugin and make a pull request.
